
[build]
# The directory where Netlify will look for serverless functions.
functions = "netlify/functions"

[build.environment]
  FIREBASE_SERVICE_ACCOUNT = "FIREBASE_SERVICE_ACCOUNT"

[[redirects]]
# Redirect all paths starting with /trip-share/ to the redirect function
from = "/trip-share/*"
to = "/.netlify/functions/createOGPage"
status = 200
force = true

[[redirects]]
from = "/trip-invitation/*"
to = "/.netlify/functions/universalRedirect"
status = 200

[[redirects]]
from = "/monarch-share/*"
to = "/.netlify/functions/universalRedirect"
status = 200

[[redirects]]
from = "/monarch-invitation/*"
to = "/.netlify/functions/universalRedirect"
status = 200

[[redirects]]
from = "/monarch-invitation/*"
to = "/.netlify/functions/universalRedirect"
status = 200